added localization support
jalantechnologies/boilerplate-next-typescript pull request #5
Opened 2021-04-12 08:26 UTC by agentraghav

## Description
Added localization support by using the next-18next package. Created localization for default English language and french. Created there localize JSON inside public/locale folder. On clicking the change local button in UI the default language English text changes to the french text by switching to the localhost:3000/fr route

## Screenshot
- For the English language
![Screenshot at 2021-04-12 13-46-26](https://user-images.githubusercontent.com/35917821/114363464-0cf95a80-9b96-11eb-8a43-d302a5fd8677.png)

- For french language
![Screenshot at 2021-04-12 13-46-45](https://user-images.githubusercontent.com/35917821/114363593-2b5f5600-9b96-11eb-897a-7bbda624f4c6.png)

## Tests
- Manual test case done 

### Automated test cases added
- NA

### Manual test cases run
The manual test case done, added "hello world" as a title in public/locale/en/common.json localize file and "Bonjour le monde" title in public/locale/fr/common.json localize file.

### Browsers tested
- [ ] Chrome
- [ ] Safari
- [ ] Internet Explorer
- [ ] Firefox

## Platform dependencies
Does this depend on or impact
- [ ] iOS
- [ ] Android
- [ ] API

2021-04-12 10:30 UTC, vindru approved these changes

2021-04-14 07:19 UTC, jjalan commented
@agentraghav - The route should not change to `localhost/fr`.

2021-04-14 07:20 UTC, jjalan requested changes
url should not change because the language changed.

2021-04-14 07:20 UTC, jjalan commented on pages/_app.tsx
> +const MyApp = ({ Component, pageProps }: AppProps) => (
Use React functional component

2021-04-14 12:58 UTC, agentraghav commented on pages/_app.tsx
> +const MyApp = ({ Component, pageProps }: AppProps) => (
done

2021-04-15 12:31 UTC, merged